---
abstract: 'return across multiple call levels'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Return-MultiLevel
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  parent: 0
  perl: 5.008000
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/mauke/Return-MultiLevel.git
version: 0.03
